//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowWealth.Pages.Member
{


    public partial class CoursePage
    {

        protected global::System.Web.UI.WebControls.Panel pnlCatalogue;

        protected global::System.Web.UI.WebControls.Repeater rptCourses;

        protected global::System.Web.UI.WebControls.Panel pnlDetail;

        protected global::System.Web.UI.WebControls.LinkButton lnkBack;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl tagDifficulty;

        protected global::System.Web.UI.WebControls.Literal litDifficulty;

        protected global::System.Web.UI.WebControls.Literal litCourseTitle;

        protected global::System.Web.UI.WebControls.Literal litCourseDesc;

        protected global::System.Web.UI.WebControls.Literal litMetaModules;

        protected global::System.Web.UI.WebControls.Literal litMetaHours;

        protected global::System.Web.UI.WebControls.Literal litMetaLevel;

        protected global::System.Web.UI.WebControls.Repeater rptModules;

        protected global::System.Web.UI.WebControls.Literal litDoneCount;

        protected global::System.Web.UI.WebControls.Literal litTotalCount;

        protected global::System.Web.UI.WebControls.Literal litTimeInvested;

        protected global::System.Web.UI.WebControls.Literal litQuizzesPassed;

        protected global::System.Web.UI.WebControls.Literal litPctSidebar;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl sidebarFill;

        protected global::System.Web.UI.WebControls.Button btnStartOrContinue;
    }
}
