//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowWealth.Pages.Member
{


    public partial class Dashboard
    {

        protected global::System.Web.UI.WebControls.Literal litWelcomeName;

        protected global::System.Web.UI.WebControls.Literal litToday;

        protected global::System.Web.UI.WebControls.Literal litCoursesEnrolled;

        protected global::System.Web.UI.WebControls.Literal litCoursesTrend;

        protected global::System.Web.UI.WebControls.Literal litModulesCompleted;

        protected global::System.Web.UI.WebControls.Literal litModulesTotal;

        protected global::System.Web.UI.WebControls.Literal litModulesTrend;

        protected global::System.Web.UI.WebControls.Literal litAvgQuizScore;

        protected global::System.Web.UI.WebControls.Literal litQuizTrend;

        protected global::System.Web.UI.WebControls.Literal litCourseCount;

        protected global::System.Web.UI.WebControls.Repeater rptCourseProgress;

        protected global::System.Web.UI.WebControls.Panel pnlNoCourses;

        protected global::System.Web.UI.WebControls.Button btnContinue;

        protected global::System.Web.UI.WebControls.Repeater rptRecentQuizzes;

        protected global::System.Web.UI.WebControls.Panel pnlNoQuizzes;

        protected global::System.Web.UI.WebControls.Repeater rptRecentActivity;

        protected global::System.Web.UI.WebControls.Panel pnlNoActivity;
    }
}
