//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowWealth.Pages.Member
{


    public partial class ModuleViewer
    {

        protected global::System.Web.UI.WebControls.HyperLink lnkBackCourse;

        protected global::System.Web.UI.WebControls.Repeater rptSideModules;

        protected global::System.Web.UI.WebControls.HyperLink lnkCrumbCourse;

        protected global::System.Web.UI.WebControls.Literal litCrumbCourse;

        protected global::System.Web.UI.WebControls.Literal litCrumbOrder;

        protected global::System.Web.UI.WebControls.Literal litModuleTitle;

        protected global::System.Web.UI.WebControls.Literal litReadingTime;

        protected global::System.Web.UI.WebControls.Literal litQuizQCount;

        protected global::System.Web.UI.WebControls.Panel pnlAlreadyDone;

        protected global::System.Web.UI.WebControls.Literal litCompletedDate;

        protected global::System.Web.UI.WebControls.Literal litModuleContent;

        protected global::System.Web.UI.WebControls.Button btnPrev;

        protected global::System.Web.UI.WebControls.Button btnMarkComplete;

        protected global::System.Web.UI.WebControls.Literal litInfoOrder;

        protected global::System.Web.UI.WebControls.Literal litInfoTime;

        protected global::System.Web.UI.WebControls.Literal litInfoQuiz;

        protected global::System.Web.UI.WebControls.Literal litInfoStatus;
    }
}
