//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowWealth.Pages.Member
{


    public partial class Profile
    {

        protected global::System.Web.UI.WebControls.Image imgProfile;

        protected global::System.Web.UI.WebControls.Literal litInitials;

        protected global::System.Web.UI.WebControls.Literal litFullNameDisplay;

        protected global::System.Web.UI.WebControls.Literal litEmailDisplay;

        protected global::System.Web.UI.WebControls.Literal litMemberSince;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl badgeStatus;

        protected global::System.Web.UI.WebControls.Literal litStatus;

        protected global::System.Web.UI.WebControls.Literal litStatCourses;

        protected global::System.Web.UI.WebControls.Literal litStatModules;

        protected global::System.Web.UI.WebControls.Literal litStatScore;

        protected global::System.Web.UI.WebControls.Panel pnlSuccess;

        protected global::System.Web.UI.WebControls.Literal litSuccessMsg;

        protected global::System.Web.UI.WebControls.Panel pnlError;

        protected global::System.Web.UI.WebControls.Literal litErrorMsg;

        protected global::System.Web.UI.WebControls.TextBox txtFullName;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFullName;

        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmail;

        protected global::System.Web.UI.WebControls.RegularExpressionValidator revEmail;

        protected global::System.Web.UI.WebControls.FileUpload fuProfilePic;

        protected global::System.Web.UI.WebControls.TextBox txtCurrentPassword;

        protected global::System.Web.UI.WebControls.TextBox txtNewPassword;

        protected global::System.Web.UI.WebControls.RegularExpressionValidator revNewPassword;

        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;

        protected global::System.Web.UI.WebControls.CompareValidator cvPassword;

        protected global::System.Web.UI.WebControls.Button btnDelete;

        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}
