//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowWealth.Pages.Member
{


    public partial class Profile
    {

        /// <summary>
        /// litInitials control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litInitials;

        /// <summary>
        /// litFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litFullName;

        /// <summary>
        /// litEmailDisplay control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litEmailDisplay;

        /// <summary>
        /// litMemberSince control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litMemberSince;

        /// <summary>
        /// badgeStatus control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl badgeStatus;

        /// <summary>
        /// litStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litStatus;

        /// <summary>
        /// pnlSuccess control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;

        /// <summary>
        /// litSuccessMsg control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litSuccessMsg;

        /// <summary>
        /// pnlError control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlError;

        /// <summary>
        /// litErrorMsg control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litErrorMsg;

        /// <summary>
        /// txtFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFullName;

        /// <summary>
        /// rfvFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFullName;

        /// <summary>
        /// txtEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// rfvEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmail;

        /// <summary>
        /// revEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revEmail;

        /// <summary>
        /// txtCurrentPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCurrentPassword;

        /// <summary>
        /// txtNewPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNewPassword;

        /// <summary>
        /// revNewPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revNewPassword;

        /// <summary>
        /// txtConfirmPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;

        /// <summary>
        /// cvPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CompareValidator cvPassword;

        /// <summary>
        /// btnSave control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSave;

        /// <summary>
        /// btnDelete control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnDelete;
    }
}