//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowWealth.Pages.Member
{


    public partial class Quiz
    {

        protected global::System.Web.UI.WebControls.Panel pnlQuestion;

        protected global::System.Web.UI.WebControls.Literal litQuizTitle;

        protected global::System.Web.UI.WebControls.Literal litCurrentNum;

        protected global::System.Web.UI.WebControls.Literal litTotalNum;

        protected global::System.Web.UI.WebControls.Literal litAnsweredCount;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl progressFill;

        protected global::System.Web.UI.WebControls.Panel pnlAlert;

        protected global::System.Web.UI.WebControls.Literal litAlertMsg;

        protected global::System.Web.UI.WebControls.Literal litQNumLabel;

        protected global::System.Web.UI.WebControls.Literal litQuestionText;

        protected global::System.Web.UI.WebControls.RadioButtonList rblOptions;

        protected global::System.Web.UI.WebControls.Button btnPrev;

        protected global::System.Web.UI.WebControls.Button btnNext;

        protected global::System.Web.UI.WebControls.Button btnSubmit;

        protected global::System.Web.UI.WebControls.Panel pnlResult;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl resultIconWrap;

        protected global::System.Web.UI.WebControls.Literal litResultIcon;

        protected global::System.Web.UI.WebControls.Literal litResultPct;

        protected global::System.Web.UI.WebControls.Literal litResultTitle;

        protected global::System.Web.UI.WebControls.Literal litResultDetail;

        protected global::System.Web.UI.WebControls.Literal litResultCorrect;

        protected global::System.Web.UI.WebControls.Literal litResultTotal;

        protected global::System.Web.UI.WebControls.Literal litResultPassMark;

        protected global::System.Web.UI.WebControls.Button btnRetry;

        protected global::System.Web.UI.WebControls.Button btnBackToCourse;
    }
}
