//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowWealth.Pages.Member
{


    public partial class VirtualLab
    {

        protected global::System.Web.UI.WebControls.TextBox txtInitial;

        protected global::System.Web.UI.WebControls.TextBox txtMonthly;

        protected global::System.Web.UI.WebControls.TextBox txtRate;

        protected global::System.Web.UI.WebControls.TextBox txtYears;

        protected global::System.Web.UI.WebControls.DropDownList ddlCompounding;

        protected global::System.Web.UI.WebControls.Button btnCalc;

        protected global::System.Web.UI.WebControls.Panel pnlEmpty;

        protected global::System.Web.UI.WebControls.Panel pnlResults;

        protected global::System.Web.UI.WebControls.Literal litFinalValue;

        protected global::System.Web.UI.WebControls.Literal litTotalInvested;

        protected global::System.Web.UI.WebControls.Literal litInterest;

        protected global::System.Web.UI.WebControls.Literal litROI;

        protected global::System.Web.UI.WebControls.Repeater rptYearly;
    }
}
