//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowWealth
{


    public partial class after_landing
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// litUserName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litUserName;

        /// <summary>
        /// lsLogout control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LoginStatus lsLogout;

        /// <summary>
        /// lnkDashboard control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkDashboard;

        /// <summary>
        /// lnkCourses control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkCourses;

        /// <summary>
        /// lnkVirtualLab control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkVirtualLab;

        /// <summary>
        /// lnkProfile control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkProfile;

        /// <summary>
        /// pnlAdminLinks control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlAdminLinks;
    }
}