//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowWealth.Master
{


    public partial class before_landing
    {

        protected global::System.Web.UI.HtmlControls.HtmlHead head1;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;

        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
