//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowWealth.Pages.Admin
{


    public partial class ManageQuiz
    {

        protected global::System.Web.UI.WebControls.Panel pnlSuccess;

        protected global::System.Web.UI.WebControls.Literal litSuccess;

        protected global::System.Web.UI.WebControls.Panel pnlError;

        protected global::System.Web.UI.WebControls.Literal litError;

        protected global::System.Web.UI.WebControls.DropDownList ddlCourse;

        protected global::System.Web.UI.WebControls.DropDownList ddlModule;

        protected global::System.Web.UI.WebControls.Panel pnlQuiz;

        protected global::System.Web.UI.WebControls.Literal litQuizTitle;

        protected global::System.Web.UI.WebControls.Literal litQuestionCount;

        protected global::System.Web.UI.WebControls.Literal litAttemptCount;

        protected global::System.Web.UI.WebControls.TextBox txtPassMark;

        protected global::System.Web.UI.WebControls.Button btnSavePassMark;

        protected global::System.Web.UI.WebControls.Panel pnlQuestions;

        protected global::System.Web.UI.WebControls.Repeater rptQuestions;

        protected global::System.Web.UI.WebControls.Panel pnlEmpty;

        protected global::System.Web.UI.WebControls.Button btnSaveAll;

        protected global::System.Web.UI.WebControls.Button btnAddQuestion;
    }
}
