//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowWealth.Pages.Admin
{


    public partial class ManageUser
    {

        protected global::System.Web.UI.WebControls.Panel pnlSuccess;

        protected global::System.Web.UI.WebControls.Literal litSuccess;

        protected global::System.Web.UI.WebControls.Panel pnlError;

        protected global::System.Web.UI.WebControls.Literal litError;

        protected global::System.Web.UI.WebControls.Panel pnlEditForm;

        protected global::System.Web.UI.WebControls.Literal litEditHeader;

        protected global::System.Web.UI.WebControls.Literal litDetailEnrols;

        protected global::System.Web.UI.WebControls.Literal litDetailModules;

        protected global::System.Web.UI.WebControls.Literal litDetailAttempts;

        protected global::System.Web.UI.WebControls.Literal litDetailAvg;

        protected global::System.Web.UI.WebControls.Literal litDetailLastLogin;

        protected global::System.Web.UI.WebControls.Literal litDetailJoined;

        protected global::System.Web.UI.WebControls.TextBox txtFullName;

        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        protected global::System.Web.UI.WebControls.DropDownList ddlRole;

        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;

        protected global::System.Web.UI.WebControls.Button btnSave;

        protected global::System.Web.UI.WebControls.Button btnCancel;

        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        protected global::System.Web.UI.WebControls.DropDownList ddlFilterRole;

        protected global::System.Web.UI.WebControls.DropDownList ddlFilterStatus;

        protected global::System.Web.UI.WebControls.Button btnFilter;

        protected global::System.Web.UI.WebControls.Button btnReset;

        protected global::System.Web.UI.WebControls.Repeater rptUsers;

        protected global::System.Web.UI.WebControls.PlaceHolder pnlEmpty;
    }
}
