//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowWealth.Pages.Public
{


    public partial class Register
    {

        protected global::System.Web.UI.WebControls.Panel pnlError;

        protected global::System.Web.UI.WebControls.Literal litError;

        protected global::System.Web.UI.WebControls.TextBox txtFullName;

        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        protected global::System.Web.UI.WebControls.TextBox txtConfirm;

        protected global::System.Web.UI.WebControls.DropDownList ddlUserType;

        protected global::System.Web.UI.WebControls.CheckBox chkTerms;

        protected global::System.Web.UI.WebControls.CustomValidator cvTerms;

        protected global::System.Web.UI.WebControls.Button btnRegister;
    }
}
