//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowWealth
{


    public partial class _Default
    {

        protected global::System.Web.UI.WebControls.Repeater rptFeatured;
    }
}
